Fix filter return map not list
Code review feedback by @justb4:

- add a WFS e.g. https://geodata.nationaalgeoregister.nl/aan/wfs
- in Edit try to add any Probe for bbox query
- see error in UI (cannot add Probe)
- in log

```
File "/Users/just/project/geohealthcheck/borrob.git/GeoHealthCheck/plugins/probe/wfs.py", line 146, in expand_params
    if len(ft_namespaces) > 0:
TypeError: object of type 'filter' has no len()
```

- solution: in https://github.com/borrob/GeoHealthCheck/blob/py3/GeoHealthCheck/plugins/probe/wfs.py#L142 replace line with ft_namespaces = list(filter(None, list(ft_namespaces)))
- will look for more filter() occurrences assuming list...(ok, no other occurs)

Fixed as suggested.