Python 3 updates (#280)
* Update gitignore with database and venv

* Keep track of work file

* WIP: first updates on python3

* WIP: fix iteritems() to items()

* Fix empty tags in template

* Fix utf-8 error

* fix tagnames in templates

* Add cmp functions for run

Difference between py2 and py3: __lt__ etc should be defined.

* Fix syntax py3 in test

* Make imports relative

* Remove deprecations warnings in tests

* Update pavement to py3

* Update requirements

* Reset relative inputs

Update `raw_input` in models.py to `input` (py3 style)

* Update todolist

* Fix import for testing

* Update paver to py3

* Fix is_authenticated

* Add hash

* Rever tags|tojson

My first solution wasn't working.

* Add run_tests to paver

* Revert too enthousiastic edit

* Fix flake8 issues

* Delete work file

* Remove UTF-8 indication

Python 3 is UTF-8 by default. Als update on shebang.

* Fix typo

* Update travis to py3

* WIP: getting docker to work

Updated the docker build file and related items. Downgraded pyproj to 1.9.6 to
be able to install it under alpine linux. The docker container builds, but it
doesn't run just yet: still an issue with importing python libraries (I guess
something with absolute/relative imports).

* Fix import issue docker scripts

There was an issue with the import statements of the GeoHealthCheck module in
the docker container. Solved by adding the module to the pythonpath.

* Fix flake8 issues

The test will only run with the `tests/run_tests.sh` or `paver run_tests`.
Running the tests seperate will generate an importerror.

* Remove utf-8 decodes

* Update wfs3 probe to py3

* Remove try-import for py3

* Update documentation

Assuming that py3 will get its own release with version 0.8.0.

* Fix deprecation warning

* Fix filter return map not list

Code review feedback by @justb4:

- add a WFS e.g. https://geodata.nationaalgeoregister.nl/aan/wfs
- in Edit try to add any Probe for bbox query
- see error in UI (cannot add Probe)
- in log

```
File "/Users/just/project/geohealthcheck/borrob.git/GeoHealthCheck/plugins/probe/wfs.py", line 146, in expand_params
    if len(ft_namespaces) > 0:
TypeError: object of type 'filter' has no len()
```

- solution: in https://github.com/borrob/GeoHealthCheck/blob/py3/GeoHealthCheck/plugins/probe/wfs.py#L142 replace line with ft_namespaces = list(filter(None, list(ft_namespaces)))
- will look for more filter() occurrences assuming list...(ok, no other occurs)

Fixed as suggested.

* Fix Adding probe TMS tile

Code review feedback by @justb4:

- add TMS e.g. https://geodata.nationaalgeoregister.nl/tiles/service/tms/1.0.0
- add Probe for any GetTile
- exception:
```
File "/Users/just/project/geohealthcheck/borrob.git/GeoHealthCheck/plugins/probe/tms.py", line 110, in get_metadata
  return TileMapService(resource.url, version=version)
File "/Users/just/.pyenv/versions/3.7.1/envs/geohealthcheck3.7.1/lib/python3.7/site-packages/owslib/tms.py", line 61, in __init__
  self.version, url=self.url, un=self.username, pw=self.password
AttributeError: 'TileMapService' object has no attribute 'username'
```

-  investigating...could be due to 0.17.1 to 0.18.0 OWSLib upgrade in GHC..Yes OWSLib issue, opened: see geopython/OWSLib#614.

Fixed by downgrading to OWSLib 0.17.1. I made a note in the requirements.txt to
only upgrade to a new version when a solution to issue 614 is included.

* Fix basic auth

From code review @justb4:

- add a Resource URL that requires Basic Auth
- in Edit configure Basic Authentication: Username, Password, Save
- Test, is False
- See error message in report:

```
"message": "Perform_request Err: TypeError expected bytes-like object, not str",

```
- analysis: may be due to: https://www.reddit.com/r/learnpython/comments/7qa0at/typeerror_a_byteslike_object_is_required_not_str/ , see comment: python version you're using is python3, while your code is for python2.
  ...base64 lib now operated on bytes, not strings and bytes objects don't have replace() method
- think this needs fix here: https://github.com/borrob/GeoHealthCheck/blob/py3/GeoHealthCheck/util.py#L230 will investigate..

FIX:
Fixed by edit on resrouceauths plugin: explicity converting string to byte

* Force rerun travis with empty commit

* Fix httpStatusError

Codereview bij @justb4:
`check.py` does not give a HTTPStatusError when it should give you an error.
This is due to the difference between python 2/3 on dividing: python2 provides
floor, whil python 3 provides float.

-> Fixed as suggested

* Fix basic auth

Code review by @just4b
For a correctly encoded header string like 'Basic aWF...XS1\n'
this line gives something like 'Basic b\'aWF...XS1\\n\''
(the \n is later always stripped).

Fixed by formatting the return value

* Return of the sphinx

* Fix flake8 line length issue

* Fix auth encoding/decoding

From code review by @justb4:
6 - Auth info Decoding/Encoding Failure with Postgres

Only occurs when using Postgres, not with SQLite. Background: GHC
encodes/encrypts a generic auth dict info structure via JSON string to be stored
as textfield in DB. It decodes/decrypts when reading. This way we can support
multiple auth types with a single auth column in resource table. So this is
another encoding than in 4 for HTTP auth headers, but think similar problem.
We also need to deal with existing PG DBs that have auth columns already present
in resource table.

-  install psycopg2 : pip install psycopg2
-  used existing PG DB, only changed in config_site.py: SQLALCHEMY_DATABASE_URI
   = 'postgresql://name:passw@localhost:5432/ghc', but may create new
-  add URL Resource with Basic Auth (even does not have to have basic auth)
-  in Edit add Basic Auth Username and Password
-  click Save

Fixed by ensuring encode/decode takes `string` as input and gives `string` as
output. These methodes now use static typing. The origin of the problem was the
difference of how SQLite and Postgres store the encoded string (either as text
or in some binary form). This solution makes the encoded authentication a
string object and *not* bytes.

* Fix module import issue with paver

* Fix deprecation warning

* Adopt changes after comments by @TomKralidis